---
abstract: 'Install the Error::Pure modules.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-Error-Pure
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Error::Pure: 0.31
  Error::Pure::ANSIColor: 0.29
  Error::Pure::Always: 0.07
  Error::Pure::HTTP: 0.15
  Error::Pure::HTTP::JSON: 0.05
  Error::Pure::JSON: 0.08
  Error::Pure::NoDie: 0.05
  Error::Pure::Output::ANSIColor: 0.04
  Error::Pure::Output::JSON: 0.1
  Error::Pure::Output::Tags::HTMLCustomPage: 0.03
  Error::Pure::Output::Text: 0.24
  perl: 5.6.0
resources:
  bugtracker: https://github.com/michal-josef-spacek/Task-Error-Pure/issues
  homepage: https://github.com/michal-josef-spacek/Task-Error-Pure
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Task-Error-Pure
version: '0.04'
