---
abstract: 'Install the Error::Pure modules.'
author:
  - 'Michal Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-Error-Pure
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Error::Pure: 0.24
  Error::Pure::Always: 0.06
  Error::Pure::HTTP: 0.14
  Error::Pure::HTTP::JSON: 0.04
  Error::Pure::JSON: 0.04
  Error::Pure::NoDie: 0.04
  Error::Pure::Output::JSON: 0.1
  Error::Pure::Output::Text: 0.22
  perl: 5.6.0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Task-Error-Pure
  homepage: https://github.com/tupinek/Task-Error-Pure
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/Task-Error-Pure
version: '0.03'
